name: Publish client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'
    
    - name: Restore dependencies
      run: dotnet restore src/PersonalBests.sln
    
    - name: Build
      run: dotnet build src/PersonalBests.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test src/PersonalBests.Tests/PersonalBests.Tests.csproj --no-restore
    
    - name: Publish
      run: dotnet publish src/PersonalBests.Client/PersonalBests.Client.csproj -c Release -o publish
    
    - name: Zip the published app
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: src/PersonalBests.Client/publish/**
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./src/PersonalBests.Client/publish.zip
        asset_name: PersonalBests.Client.zip
        asset_content_type: application/zip
